### PR TITLE
Update to esp-hal 0.19

### PR DESCRIPTION
**Pull request by GnomedDev**
Compiles on my project, but needs testing by someone who has a project that actually works right now.

### CODE REVIEW

**Comment by AnthonyGrondin** [comment]
You can test that all examples build, using [just](https://github.com/casey/just), and you can also run the examples in `examples/` to test at runtime.

Ex: `SSID=<SSID> PASSWORD=<PASS> cargo +esp esp32s3 --release --example sync_server --features="esp-wifi/wifi-logs"`

Currently `esp-wifi` doesn't compile with the feature `embedded-svc` enabled:

```
error[E0063]: missing fields `pmf_cfg` and `scan_method` in initializer of `embedded_svc::wifi::ClientConfiguration`
    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-wifi-0.7.0/src/wifi/mod.rs:2751:21
     |
2751 |                     embedded_svc::wifi::ClientConfiguration {
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `pmf_cfg` and `scan_method`

error[E0063]: missing fields `pmf_cfg` and `scan_method` in initializer of `embedded_svc::wifi::ClientConfiguration`
    --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-wifi-0.7.0/src/wifi/mod.rs:2778:21
     |
2778 |                     embedded_svc::wifi::ClientConfiguration {
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `pmf_cfg` and `scan_method`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `esp-wifi` (lib) due to 2 previous errors
```

This is due to the breaking change in: https://github.com/esp-rs/embedded-svc/pull/75

**Comment by GnomedDev** [comment]
Got it, I've opened an issue on the esp-hal repo for that build failure. This is blocked on that for now.

**Comment by bjoernQ** [comment]
The good thing is that embedded-svc is totally optional - we have an inherent version of the wifi API - you would just need to adjust the imports

**Comment by GnomedDev** [comment]
CI is passing, now that https://github.com/esp-rs/esp-hal/issues/1817 is fixed.

**Review by bjoernQ — APPROVED** [review]
LGTM

**Pull request merged**
